import config from '@iobroker/eslint-config';
import globals from 'globals';

export default [
    ...config,
    {
        languageOptions: {
            parserOptions: {
                projectService: {
                    allowDefaultProject: ['*.js', '*.mjs'],
                },
                tsconfigRootDir: import.meta.dirname,
            },
        },
    },
    {
        // disable temporary the rule 'jsdoc/require-param' and enable 'jsdoc/require-jsdoc'
        rules: {
            'jsdoc/require-jsdoc': 'off',
            'jsdoc/require-param': 'off',
        },
    },
    {
        // 'test/*.js' and 'test/lib/*.js' are generated by `tsc -p test/tsconfig.build.json` from the *.ts sources
        ignores: ['*.mjs', 'admin/**/*.*', 'build/**/*.*', 'tmp/**/*', 'test/*.js', 'test/lib/*.js'],
    },
    {
        // Mocha test files (specs are CommonJS .js, mocks are TypeScript .ts)
        files: ['test/**/*.js', 'test/**/*.ts'],
        languageOptions: {
            globals: {
                ...globals.mocha,
            },
        },
    },
    {
        // The adapter mock forwards raw callback errors when rejecting its promise wrappers.
        files: ['test/lib/*.ts'],
        rules: {
            '@typescript-eslint/prefer-promise-reject-errors': 'off',
        },
    },
    {
        // Test specs load the compiled adapter under test (build/, which ships no type
        // declarations and lives outside the test rootDir) and untyped helpers via require().
        files: ['test/*.ts'],
        rules: {
            '@typescript-eslint/no-require-imports': 'off',
        },
    },

];
